// Builds dist/families/stars/stars.json, the Clockwork Gates stars group, from
// the authoring list below. Each puzzle's answers (the hops or rings that
// reach its goal, or each round's marks) are computed here by drawing
// (dist/families/stars/stars.js) and checked again against gcd by
// scripts/validate-stars.mjs. Design notes and sources: docs/stars/README.md.
import {writeFile} from 'node:fs/promises';
import {pieces, roundAnswer} from '../dist/families/stars/stars.js';

const WEEK4 = 'https://github.com/jamesrp/math-circle-worksheets/tree/main/lowell-math-circle-year-2/week-04';
export const sources = [
  {id: 'stars-week04', title: 'Bellingham Math Circle — Week 4: Stars and code wheels, packets, return visit and adult guides', url: WEEK4, kind: 'local curriculum'},
  {id: 'stars-coxeter', title: 'H. S. M. Coxeter — Regular Polytopes (1973), §2.8 on star polygons {n/k}', url: 'https://en.wikipedia.org/wiki/Regular_Polytopes_(book)', kind: 'research'},
  {id: 'stars-cyclic', title: 'Subgroups and cosets of the cyclic group ℤ/n: the orbits of x ↦ x + k are the cosets of the subgroup generated by gcd(n, k)', url: 'https://en.wikipedia.org/wiki/Cyclic_group#Subgroups_and_notation', kind: 'undergraduate'}
];
export const family = {
  id: 'stars',
  title: 'Clockwork Gates stars',
  mathematics: 'Hopping k places around n evenly spaced dots and drawing each hop as a straight line splits the dots into gcd(n, k) pieces, each a star or polygon through n / gcd(n, k) dots: the orbits of x ↦ x + k in the cyclic group of order n are the cosets of the subgroup generated by gcd(n, k). One hop reaches every dot exactly when n and k share no factor, so every hop draws a single piece exactly when n is prime. Hop k and hop n − k draw the same picture, and a piece of hop k on n dots is the star polygon {m/j} with m = n / gcd(n, k) and j = k / gcd(n, k).',
  rules: [
    'A hop of k draws a straight line to the dot k places clockwise.',
    'Keep hopping until the line comes back, then start again at a dot with no line.',
    'The drawing is finished when every dot has a line. Each start makes one piece.'
  ],
  sourceIds: sources.map(s => s.id)
};

const RULES = family.rules;
const CONTROLS = {
  draw: 'Tap a dot to start. Then tap the dot the hop lands on, counting clockwise. When the line comes back to its start, tap a dot with no line to start again. A wrong dot shakes. Again clears the drawing; Undo takes back one tap.',
  starts: 'Tap a dot to start, then tap another dot: that first line sets the hop. Keep tapping where the hop lands, counting clockwise. When the line comes back, tap a dot with no line to start again. Again clears the drawing and the hop; Undo takes back one tap.',
  decide: 'Tap a dot to start, then tap another dot: that first line sets the hop. Keep tapping where the hop lands, counting clockwise. When the line comes back, tap a dot with no line to start again. Again clears the drawing and the hop. After one finished drawing, “No hop makes …” becomes available; a wrong claim is refused.',
  rings: 'Choose a ring. Tap a dot to start, then tap the dot the hop lands on, counting clockwise. When the line comes back, tap a dot with no line to start again. Again clears the drawing; Undo takes back one tap.',
  match: 'Choose a ring. Tap a dot to start, then tap another dot: that first line sets the hop. Keep tapping where the hop lands. When the line comes back, tap a dot with no line to start again. Again clears the drawing and the hop.',
  every: 'Tap every number that belongs, then Check. You get one check; after a miss, Next brings a new question.'
};
const range = (a, b) => Array.from({length: b - a + 1}, (_, i) => a + i);

const authored = [
  {
    number: 1, difficulty_level: 'easy', title: 'Five dots, hop 2',
    parameters: {mode: 'draw', dots: 5, hop: 2},
    objective: 'Draw hop 2 until every dot has a line.',
    idea: 'Hop 2 on 5 dots reaches every dot and draws a five-pointed star.',
    prerequisites: 'Count to 2 along a ring. Nothing to read.',
    hints: ['Tap any dot. Then count 2 dots clockwise and tap where you land.', 'Keep hopping 2 until you are back where you started.', 'One start is enough: every dot gets a line.'],
    parent: {
      notice: 'Whether your child counts the next dot as “one”, not the dot the pen is on.',
      prompt: 'Did every dot get a line before you came back?',
      explanation: 'Hop 2 on 5 dots lands on 2, 4, 1, 3 and back to 0, so one start reaches every dot. The picture is the star polygon {5/2}.',
      extension: 'Which hops on 5 dots come back early?',
      connection: 'The orbit of 0 under adding 2 in the cyclic group of order 5 is the whole group, because 2 and 5 share no factor.'
    },
    provenance: 'Week 4 whole-group launch: hop 2 on a ring of 5.'
  },
  {
    number: 2, difficulty_level: 'easy', title: 'Six dots, hop 2',
    parameters: {mode: 'draw', dots: 6, hop: 2},
    objective: 'Draw hop 2 until every dot has a line.',
    idea: 'Hop 2 on 6 dots comes back early, so the drawing needs a second start: two triangles.',
    prerequisites: 'Stars puzzle 1.',
    hints: ['Hop 2 until the line comes back. Do some dots still have no line?', 'Start again at a dot with no line, and hop 2 again.', 'Two starts, two triangles.'],
    parent: {
      notice: 'Whether your child finds the empty dots and starts again without being told.',
      prompt: 'Why did the line come back before reaching every dot?',
      explanation: 'Hop 2 on 6 dots only lands on 0, 2 and 4, so the other three dots need a second start. 2 and 6 share the factor 2, and there are 2 pieces.',
      extension: 'Which hops on 6 dots need only one start?',
      connection: 'The orbits of adding 2 are the cosets of the subgroup {0, 2, 4}: the even and the odd dots.'
    },
    provenance: 'Week 4 K–1 Problem 3 (ring of 6, hops 1, 2, 3).'
  },
  {
    number: 3, difficulty_level: 'easy', title: 'Two pieces on eight',
    parameters: {mode: 'starts', dots: 8, starts: 2},
    objective: 'Choose a hop by drawing the first line, then keep hopping until every dot has a line. Finish with exactly 2 pieces.',
    visibleObjective: 'Make 2 pieces.',
    idea: 'On 8 dots, hops 2 and 6 make 2 pieces; the other hops make 1 or 4.',
    prerequisites: 'Stars puzzles 1 and 2.',
    hints: ['Your first line sets the hop. Try a hop and see how many starts it needs.', 'Hops 1, 3, 5 and 7 need one start. Try an even hop.', 'Hop 2 makes two squares.'],
    parent: {
      notice: 'Whether your child predicts before drawing after a try or two.',
      prompt: 'Which hops needed only one start? Which needed more?',
      explanation: 'On 8 dots, hops 1, 3, 5 and 7 reach every dot; hops 2 and 6 make two squares; hop 4 makes four lines. The number of pieces is the biggest number that goes evenly into both 8 and the hop.',
      extension: 'Can you predict the number of pieces for hop 6 before drawing it?',
      connection: 'The number of pieces is gcd(8, k).'
    },
    provenance: 'Week 4 grades 2–3 Problem 1 (8 dots, hops 1 to 4), turned around: the number of pieces is given.'
  },
  {
    number: 4, difficulty_level: 'medium', title: 'Three pieces on twelve',
    parameters: {mode: 'starts', dots: 12, starts: 3, decide: true},
    objective: 'Choose a hop by drawing the first line, then keep hopping until every dot has a line. Finish with exactly 3 pieces, or say that no hop can.',
    visibleObjective: 'Make 3 pieces, or say that no hop can.',
    idea: 'Three pieces on 12 dots needs pieces of 4 dots, and hop 3 (or 9) makes three squares.',
    prerequisites: 'Stars puzzles 1–3.',
    hints: ['Every piece has the same number of dots. How many dots would each of 3 pieces have?', 'A piece with 4 dots is a square. Which hop draws one?', 'Hop 3 makes three squares.'],
    parent: {
      notice: 'Whether your child reasons from the size of a piece (12 ÷ 3 = 4 dots) rather than trying every hop.',
      prompt: 'If there are 3 pieces, how many dots does each one have?',
      explanation: 'All pieces are turned copies of the first, so 3 pieces on 12 dots have 4 dots each. Hop 3 lands on 0, 3, 6, 9: a square. Hop 9 draws the same squares backward. Hop 6 makes 6 pieces, and hops 2 and 4 make 2 and 4. The “no hop can” button is there for puzzle 5; here it is refused.',
      extension: 'On 12 dots, which numbers of pieces are possible?',
      connection: 'The pieces are cosets of a subgroup, so they all have the same size, and that size divides 12 (Lagrange’s theorem in its smallest form).'
    },
    provenance: 'Week 4 grades 2–3 Problem 7 (a hop that makes exactly 3 starts, on rings of 9, 16, 18 and 15 dots), on a new ring of 12, with the option to say that no hop can.'
  },
  {
    number: 5, difficulty_level: 'medium', title: 'Three pieces on sixteen',
    parameters: {mode: 'starts', dots: 16, starts: 3, decide: true},
    objective: 'Choose a hop by drawing the first line, then keep hopping until every dot has a line. Finish with exactly 3 pieces, or say that no hop can.',
    visibleObjective: 'Make 3 pieces, or say that no hop can.',
    idea: 'No hop makes 3 pieces on 16 dots: the pieces all have the same number of dots, and 16 dots do not split into 3 equal piles.',
    prerequisites: 'Stars puzzle 4.',
    hints: ['How many dots would each of 3 pieces have?', 'Every piece has the same number of dots. Can 16 dots make 3 equal piles?', 'They can’t, so no hop makes 3 pieces. Finish one drawing, then say so.'],
    parent: {
      notice: 'Whether your child tries every hop or stops once they see that the pieces must be equal.',
      prompt: 'How do you know that no hop works, without trying them all?',
      explanation: 'Every piece is a turned copy of the first, so the pieces have equal numbers of dots and split 16 into equal piles. 16 does not split into 3 equal piles (16 = 5 + 5 + 6 at best), so no hop makes 3 pieces. The hops from 1 to 15 make 1, 2, 4 or 8 pieces.',
      extension: 'On 16 dots, which numbers of pieces can a hop make?',
      connection: 'The number of pieces is gcd(16, k), a divisor of 16; 3 is not one. The equal piles are the cosets of a subgroup, all the same size.'
    },
    provenance: 'Week 4 grades 2–3 Problem 7 (“can’t” for 16 dots and 3 starts); the certificate is the review card’s: 3 pieces on 16 dots would need 3 equal piles.'
  },
  {
    number: 6, difficulty_level: 'medium', title: 'Hop 6, three pieces',
    parameters: {mode: 'rings', hop: 6, starts: 3, choices: range(7, 16)},
    objective: 'Choose a ring of dots. Draw hop 6 until every dot has a line, and finish with exactly 3 pieces.',
    visibleObjective: 'Make 3 pieces.',
    idea: 'Hop 6 makes 3 pieces on rings that 3 goes into but 2 doesn’t: 9 and 15.',
    prerequisites: 'Stars puzzles 1–5.',
    hints: ['Hop 6 on 12 dots makes 6 pieces. What would make it 3?', 'The ring needs 3 as a factor, but not 2.', 'Try 9 dots.'],
    parent: {
      notice: 'Whether your child tries rings at random or looks for a ring that 3 goes into.',
      prompt: 'What do 6 and the ring have to share?',
      explanation: 'Hop 6 on n dots makes gcd(n, 6) pieces. That is 3 exactly when 3 divides n and 2 doesn’t: 9 and 15 among 7 to 16.',
      extension: 'With hop 6, which rings make 2 pieces?',
      connection: 'gcd(n, 6) = 3 for n = 9, 15.'
    },
    provenance: 'Week 4 grades 2–3 Problem 7 (find a hop that makes 3 starts), with the hop given and the ring to choose. New instance.'
  },
  {
    number: 7, difficulty_level: 'medium', title: 'The eight-pointed star',
    parameters: {mode: 'match', target: {dots: 8, hop: 3}, choices: range(5, 12)},
    objective: 'Draw the picture on the card. Choose a ring, then a hop, and draw until every dot has a line.',
    visibleObjective: 'Draw the picture.',
    idea: 'Eight points and one piece: 8 dots, hop 3 (or 5).',
    prerequisites: 'Stars puzzles 1–5.',
    hints: ['Count the points of the star. How many dots does the ring need?', 'It is one piece through 8 dots. Which hops on 8 make one piece?', 'Hop 3 on 8 dots.'],
    parent: {
      notice: 'Whether your child counts points to choose the ring first.',
      prompt: 'How many dots did the picture use? How many pieces does it have?',
      explanation: 'The star has 8 points and is one piece, so it uses 8 dots and a hop that shares no factor with 8. Hop 1 draws the octagon and hop 3 the star {8/3}; hop 5 draws the same star backward.',
      extension: 'Is there a star with 6 points drawn in one piece?',
      connection: 'The star polygon {8/3}.'
    },
    provenance: 'Week 4 grades 4–5 Problem 9 (find the dots and hop of an erased drawing). New instance.'
  },
  {
    number: 8, difficulty_level: 'hard', title: 'Hop 8, four pieces',
    parameters: {mode: 'rings', hop: 8, starts: 4, choices: range(9, 20)},
    objective: 'Choose a ring of dots. Draw hop 8 until every dot has a line, and finish with exactly 4 pieces.',
    visibleObjective: 'Make 4 pieces.',
    idea: 'Hop 8 makes 4 pieces when 4 goes into the ring but 8 doesn’t: 12 and 20.',
    prerequisites: 'Stars puzzle 6.',
    hints: ['What must 8 and the ring share for 4 pieces?', 'The ring needs 4 as a factor, but not 8.', 'Try 12 dots.'],
    parent: {
      notice: 'Whether your child rules out 16 (8 pieces) without drawing it.',
      prompt: 'Why does 16 give too many pieces?',
      explanation: 'Hop 8 on n dots makes gcd(n, 8) pieces: 4 exactly when n is a multiple of 4 but not of 8, so 12 and 20 among 9 to 20. On 12 dots each piece is a triangle; on 20 dots each is a five-pointed star.',
      extension: 'On 20 dots, hop 8 draws four stars. Which other hop on 20 draws the same picture?',
      connection: 'gcd(n, 8) = 4 for n = 12, 20; on 20 dots the pieces are {5/2}.'
    },
    provenance: 'Week 4 grades 4–5 Problems 2–3 (how many pieces, without drawing), turned around. New instance.'
  },
  {
    number: 9, difficulty_level: 'hard', title: 'Two stars',
    parameters: {mode: 'match', target: {dots: 10, hop: 4}, choices: range(5, 16)},
    objective: 'Draw the picture on the card. Choose a ring, then a hop, and draw until every dot has a line.',
    visibleObjective: 'Draw the picture.',
    idea: 'Two five-pointed stars: 10 dots, and a hop that makes 2 pieces with a jump of 2 inside each star.',
    prerequisites: 'Stars puzzles 5 and 7.',
    hints: ['How many pieces? How many points on each?', 'Two pieces of 5 points need 10 dots. Which hops on 10 make 2 pieces?', 'Hop 4 on 10 dots.'],
    parent: {
      notice: 'Whether your child separates the two questions: how many dots, then which hop.',
      prompt: 'Hops 2 and 4 both make 2 pieces on 10 dots. Which one draws stars?',
      explanation: 'Two pieces of 5 points use 10 dots, so the hop shares exactly 2 with 10: 2, 4, 6 or 8. Inside each piece the hop jumps k ÷ 2 points of a 5-point ring, so hop 2 draws pentagons and hop 4 (or 6) draws stars.',
      extension: 'Draw three five-pointed stars. How many dots, and which hop?',
      connection: 'Hop k on n dots draws gcd(n, k) copies of {m/j}, with m = n / gcd(n, k) and j = k / gcd(n, k).'
    },
    provenance: 'Week 4 grades 4–5 Problem 9 (erased drawings: find the dots and the hop). New instance.'
  },
  {
    number: 10, difficulty_level: 'hard', title: 'Three stars',
    parameters: {mode: 'match', target: {dots: 15, hop: 6}, choices: range(5, 18)},
    objective: 'Draw the picture on the card. Choose a ring, then a hop, and draw until every dot has a line.',
    visibleObjective: 'Draw the picture.',
    idea: 'Three five-pointed stars: 15 dots and hop 6 (or 9).',
    prerequisites: 'Stars puzzle 9.',
    hints: ['How many pieces, and how many points on each?', 'Three stars of 5 points use 15 dots. Inside each star the hop jumps 2 points.', 'Hop 6 on 15 dots.'],
    parent: {
      notice: 'Whether your child uses puzzle 9’s reasoning: 3 × 5 dots, then 3 × 2 for the hop.',
      prompt: 'How far does the hop go inside one star? How far is that on the whole ring?',
      explanation: 'Three pieces of 5 points use 15 dots, so gcd(15, k) = 3 and k = 3, 6, 9 or 12. Inside each piece the hop jumps k ÷ 3 points of a 5-point ring: 1 for a pentagon (k = 3 or 12), 2 for a star (k = 6 or 9).',
      extension: 'Which pictures on 15 dots have exactly 5 pieces?',
      connection: 'Compound star figures: gcd(n, k) rotated copies of {m/j}.'
    },
    provenance: 'Week 4 grades 4–5 Problem 9 (erased drawings), at a size where trying every hop is slow. New instance.'
  },
  {
    number: 11, difficulty_level: 'hard', title: 'Every one-piece hop',
    parameters: {mode: 'every', ask: 'hops', rounds: [30, 24, 36, 20]},
    objective: 'Tap every hop that draws one piece on this ring, then Check.',
    visibleObjective: 'Tap every hop that makes one piece.',
    idea: 'A hop makes one piece exactly when it shares no factor with the number of dots.',
    prerequisites: 'Stars puzzles 1–8. Knowing small factors helps.',
    hints: ['Which numbers go evenly into the number of dots?', 'A hop that shares any of those factors comes back early.', 'Keep only the hops that share no factor with the dots.'],
    parent: {
      notice: 'Whether your child crosses off multiples of each factor rather than imagining each drawing.',
      prompt: 'How can you tell, without drawing, that hop 9 on 30 dots comes back early?',
      explanation: 'Hop k on n dots makes gcd(n, k) pieces, so one piece means gcd(n, k) = 1. On 30 dots that leaves 1, 7, 11, 13, 17, 19, 23 and 29: eight hops, which is φ(30). There is one check per ring; after a miss the answer is shown and Next brings a different ring.',
      extension: 'On 30 dots, how many hops make exactly 2 pieces?',
      connection: 'The hops that make one piece are the generators of the cyclic group of order n; there are φ(n) of them (Euler’s totient).'
    },
    provenance: 'Week 4 grades 4–5 Problems 3 and 7 (the rule for the number of pieces), asked at a size where drawing every hop is slow; idea from docs/insight-without-ai.md (“tap every jump that visits all 30 places”).'
  },
  {
    number: 12, difficulty_level: 'hard', title: 'Rings where every hop is one piece',
    parameters: {mode: 'every', ask: 'rings', rounds: [[4, 20], [10, 30], [20, 40]]},
    objective: 'Tap every ring on which every hop draws one piece, then Check.',
    visibleObjective: 'Tap every ring where every hop makes one piece.',
    idea: 'Every hop makes one piece exactly when the number of dots is prime.',
    prerequisites: 'Stars puzzle 11.',
    hints: ['On 12 dots, which hop comes back early? What about 13 dots?', 'A ring fails if some smaller hop shares a factor with it.', 'Keep the rings whose only factors are 1 and themselves.'],
    parent: {
      notice: 'Whether your child connects “some hop comes back early” with “the number of dots can be split evenly”.',
      prompt: 'Why does 15 fail? Which hop shows it?',
      explanation: 'If n has a factor d between 1 and n, hop d comes back after n ÷ d hops, before reaching every dot. If n is prime, every hop from 1 to n − 1 shares no factor with n. So the rings are exactly the primes: 5, 7, 11, 13, 17 and 19 between 4 and 20.',
      extension: 'Week 4 grades 4–5 Problem 8 asks you to explain why your list is complete. Can you?',
      connection: 'The cyclic group of order n has no subgroups other than itself and {0} exactly when n is prime.'
    },
    provenance: 'Week 4 grades 4–5 Problem 8 (rings from 4 to 20 where every hop reaches every dot), with two further ranges for later rounds.'
  }
];

export function answers(item) {
  const q = item.parameters;
  if (q.mode === 'draw') return {pieces: pieces(q.dots, q.hop).length};
  if (q.mode === 'starts') {
    const hops = range(1, q.dots - 1).filter(k => pieces(q.dots, k).length === q.starts);
    return q.decide ? {hops, possible: hops.length > 0} : {hops};
  }
  if (q.mode === 'rings') return {rings: q.choices.filter(n => pieces(n, q.hop).length === q.starts)};
  if (q.mode === 'match') return {pieces: pieces(q.target.dots, q.target.hop).length, hops: range(1, q.target.dots - 1).filter(k => (k - q.target.hop) % q.target.dots === 0 || (k + q.target.hop) % q.target.dots === 0)};
  return {rounds: q.rounds.map((_, i) => roundAnswer(q, i))};
}
export const puzzles = authored.map(item => {
  const solution = answers(item);
  for (const list of [solution.hops, solution.rings]) if (list && !list.length && !item.parameters.decide) throw new Error(`stars-${item.number}: no answer`);
  return {
    id: `stars-${String(item.number).padStart(2, '0')}`,
    number: item.number,
    title: item.title,
    band: 'all',
    difficulty_level: item.difficulty_level,
    mechanic: 'star',
    libraryFamily: 'clock',
    group: 'Stars',
    familyTitle: 'Clockwork Gates',
    revision: 1,
    parameters: item.parameters,
    objective: item.objective,
    visibleObjective: item.visibleObjective ?? item.objective,
    instruction: item.objective,
    controls: CONTROLS[item.parameters.decide ? 'decide' : item.parameters.mode],
    rules: item.parameters.mode === 'every' ? [...RULES, 'You get one check per question. After a miss, the answer is shown and Next brings a different question.'] : RULES,
    idea: item.idea,
    prerequisites: item.prerequisites,
    hints: item.hints,
    parent: {...item.parent, sourceIds: ['stars-week04', 'stars-cyclic', ...(/\{|star polygon/i.test(item.parent.connection + item.parent.explanation) ? ['stars-coxeter'] : [])]},
    solution,
    provenance: item.provenance,
    sourceDocument: 'docs/stars/README.md'
  };
});
export const pack = {title: 'Clockwork Gates stars', version: 1, families: [family], sources, puzzles};

if (process.argv[1] === new URL(import.meta.url).pathname) {
  await writeFile(new URL('../dist/families/stars/stars.json', import.meta.url), JSON.stringify(pack, null, 1) + '\n');
  for (const p of puzzles) console.log(p.id, p.difficulty_level, JSON.stringify(p.parameters), JSON.stringify(p.solution));
}
