// Checks the Sorting machines pack (dist/families/sorting/sorting.json):
// content fields and sources; every puzzle's facts against an independent
// simulator (lanes as objects, starts generated by Heap's algorithm and by
// counting); the theorems the notes rely on, over every machine of the sizes
// used (the 0–1 principle, the light-pattern bound, the fewest bars); hint
// chains to a solve; illegal moves; forged saves; and the playground.
// Run: node scripts/validate-sorting.mjs
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {freshAttempt, move, isSolved, nextHint, validBoard, undo} from '../dist/engine.js';
import {isExpansion, mechanicFor} from '../dist/expansion.js';
import {breakers, failures, sortsAll} from '../dist/families/sorting/sorting.js';
import {loadPack} from './packs.mjs';

// An independent simulator. A machine is a list of {top, bottom} lanes
// numbered from 1, as the pack writes them; a start is an object lane → value.
const asLanes = list => Object.fromEntries(list.map((v, i) => [i + 1, v]));
const asList = (lanes, n) => Array.from({length: n}, (_, i) => lanes[i + 1]);
function simulate(machine, start) {
  const lanes = asLanes(start), lit = [];
  for (const bar of machine) {
    if (!bar) { lit.push(0); continue; }
    const {top, bottom} = bar, low = Math.min(lanes[top], lanes[bottom]), high = Math.max(lanes[top], lanes[bottom]);
    lit.push(lanes[top] === high && high !== low ? 1 : 0);
    lanes[top] = low; lanes[bottom] = high;
  }
  const finish = asList(lanes, start.length);
  return {finish, lit: lit.join(''), sorted: finish.every((v, i) => i === 0 || finish[i - 1] <= v)};
}
// Heap's algorithm, a different generator from the module's.
function heap(n) {
  const a = Array.from({length: n}, (_, i) => i + 1), c = Array(n).fill(0), out = [[...a]];
  let i = 0;
  while (i < n) {
    if (c[i] < i) { const j = i % 2 ? c[i] : 0; [a[j], a[i]] = [a[i], a[j]]; out.push([...a]); c[i]++; i = 0; } else { c[i] = 0; i++; }
  }
  return out;
}
const counting = n => Array.from({length: 1 << n}, (_, m) => m.toString(2).padStart(n, '0').split('').map(Number));
const inputs = (n, cards) => cards === 'binary' ? counting(n) : heap(n);
const fromPack = machine => machine.map(([top, bottom]) => ({top, bottom}));
const fromBoard = bars => bars.map(bar => bar && {top: bar[0] + 1, bottom: bar[1] + 1});
const wrongStarts = (machine, n, cards) => inputs(n, cards).filter(s => !simulate(machine, s).sorted).map(s => s.join('')).sort();
const sorts = (machine, n) => heap(n).every(s => simulate(machine, s).sorted);
// A finish that no one extra bar puts in order.
const pastFixing = finish => !allMachines(finish.length, 1).some(([bar]) => simulate([bar], finish).sorted);
function allMachines(n, k, adjacent = false, withEmpty = false) {
  const bars = [];
  for (let top = 1; top <= n; top++) for (let bottom = top + 1; bottom <= n; bottom++) if (!adjacent || bottom === top + 1) bars.push({top, bottom});
  const choices = withEmpty ? [null, ...bars] : bars;
  let out = [[]];
  for (let s = 0; s < k; s++) out = out.flatMap(m => choices.map(b => [...m, b]));
  return out;
}

// Theorems, checked over every machine of the sizes the puzzles use.
function theorems() {
  for (const [n, k] of [[3, 0], [3, 1], [3, 2], [3, 3], [3, 4], [4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5]]) {
    for (const machine of allMachines(n, k)) {
      // The 0–1 principle: sorting every 0–1 start is the same as sorting every start.
      const binary = counting(n).every(s => simulate(machine, s).sorted);
      assert.equal(binary, sorts(machine, n), `0–1 principle, ${n} lanes`);
      // Starts that light the same bars finish in different orders.
      const seen = new Map();
      for (const s of heap(n)) {
        const r = simulate(machine, s), other = seen.get(r.lit);
        if (other) assert.notEqual(other.finish.join(''), r.finish.join(''), 'shared lights, different finishes');
        seen.set(r.lit, r);
      }
      assert.ok(seen.size <= 2 ** k, 'k bars light in at most 2^k ways');
      // The module agrees with the simulator.
      const bars = machine.map(({top, bottom}) => [top - 1, bottom - 1]);
      assert.equal(sortsAll(bars, n), sorts(machine, n));
    }
  }
  const count = (n, k, adjacent) => allMachines(n, k, adjacent).filter(m => sorts(m, n)).length;
  const facts = {three2: count(3, 2), three3: count(3, 3), four4: count(4, 4), four5: count(4, 5), neighbors5: count(4, 5, true), neighbors6: count(4, 6, true)};
  assert.deepEqual(facts, {three2: 0, three3: 6, four4: 0, four5: 12, neighbors5: 0, neighbors6: 16}, 'fewest bars: 3 for three lanes, 5 for four, 6 for four neighbors only');
  return facts;
}

export async function validateSorting() {
  const read = async path => JSON.parse(await readFile(new URL(path, import.meta.url), 'utf8'));
  const sorting = await read('../dist/families/sorting/sorting.json'), {puzzles: all, sources} = await loadPack();
  assert.equal(new Set(all.map(p => p.id)).size, all.length, 'puzzle ids are unique across the packs');
  assert.equal(new Set(sources.map(s => s.id)).size, sources.length, 'source ids are unique across the packs');
  for (const s of sorting.sources) { assert.match(s.url, /^https:\/\//); assert.ok(s.title && s.kind); }
  assert.equal(sorting.families.length, 1);
  const family = sorting.families[0];
  assert.equal(family.id, 'sorting'); assert.ok(family.title && family.mathematics && family.rules.length);
  const core = sorting.puzzles.filter(p => p.band === 'all'), playgrounds = sorting.puzzles.filter(p => p.band === 'playground');
  assert.equal(playgrounds.length, 1); assert.equal(core.length + 1, sorting.puzzles.length);
  assert.ok(core.length >= 8 && core.length <= 12, '8 to 12 puzzles');
  assert.deepEqual(core.map(p => p.number), core.map((_, i) => i + 1), 'numbers run 1..n');
  for (const level of ['easy', 'medium', 'hard']) assert.ok(core.some(p => p.difficulty_level === level), level);
  for (const p of sorting.puzzles) {
    assert.equal(p.mechanic, 'sorting'); assert.ok(isExpansion(p)); assert.equal(p.revision, 1);
    assert.ok(p.id === 'sorting-playground' || p.id === `sorting-${String(p.number).padStart(2, '0')}`, `${p.id}: id`);
    for (const key of ['title', 'instruction', 'objective', 'controls', 'idea', 'prerequisites', 'familyTitle', 'provenance']) assert.ok(typeof p[key] === 'string' && p[key].trim(), `${p.id} ${key}`);
    assert.ok(p.rules.length && p.rules.every(r => r.trim())); assert.equal(p.hints.length, 3); p.hints.forEach(h => assert.ok(h.trim()));
    for (const key of ['notice', 'prompt', 'explanation', 'extension', 'connection']) assert.ok(p.parent[key]?.trim(), `${p.id} parent.${key}`);
    for (const id of p.parent.sourceIds) assert.ok(sources.some(s => s.id === id), `${p.id} ${id}`);
  }
  const facts = theorems();

  let steps = 0;
  const answers = {};
  for (const p of core) {
    const q = p.parameters, n = q.lanes, machine = fromPack(q.machine);
    // The facts each puzzle relies on.
    if (q.mode === 'break' || q.mode === 'every') {
      let wrong = wrongStarts(machine, n, q.cards);
      assert.deepEqual(failures(q.machine.map(([a, b]) => [a - 1, b - 1]), n, q.cards).map(s => s.join('')).sort(), wrong, `${p.id}: wrong starts`);
      if (q.target === 'unfixable') {
        wrong = wrong.filter(k => pastFixing(simulate(machine, k.split('').map(Number)).finish));
        // One such start proves no single extra bar repairs the machine.
        assert.ok(!allMachines(n, 1).some(([bar]) => sorts([...machine, bar], n)), `${p.id}: no one bar repairs it`);
      }
      assert.ok(wrong.length, `${p.id}: the machine gets some start wrong`);
      assert.deepEqual(breakers(q).map(s => s.join('')).sort(), wrong, `${p.id}: the starts that count`);
      assert.ok(simulate(machine, q.start).sorted, `${p.id}: the first Run comes out in order, so the search is the child's`);
      answers[p.id] = wrong;
    }
    if (q.mode === 'lights') {
      const groups = new Map();
      for (const s of heap(n)) { const lit = simulate(machine, s).lit; groups.set(lit, [...(groups.get(lit) || []), s.join('')]); }
      assert.ok(2 ** machine.length < heap(n).length, `${p.id}: fewer light patterns than starts`);
      answers[p.id] = [...groups.values()].filter(g => g.length > 1).length;
    }
    if (q.mode === 'build') {
      const open = q.slots - machine.length;
      const fills = allMachines(n, open, q.adjacent, true).filter(f => sorts([...machine, ...f], n));
      assert.ok(fills.length, `${p.id}: solvable`);
      if (machine.length) assert.ok(!sorts(machine, n), `${p.id}: the given bars do not already sort`);
      else assert.ok(!allMachines(n, q.slots - 1, q.adjacent).some(m => sorts(m, n)), `${p.id}: the slots are the fewest that can sort`);
      answers[p.id] = fills.length;
    }
    // Hints alone reach a solve, and every hint is a legal move.
    let a = freshAttempt(p);
    assert.ok(validBoard(p, a.board) && !isSolved(p, a.board), `${p.id}: valid unsolved start`);
    for (let i = 0; !isSolved(p, a.board) && i < 100; i++) {
      const hint = nextHint(p, a);
      assert.equal(hint.type, 'move', `${p.id}: ${hint.text}`);
      const next = move(p, a, hint.action);
      assert.ok(next && next !== a, `${p.id}: hint ${JSON.stringify(hint.action)} is legal`);
      a = next; steps++;
    }
    assert.ok(isSolved(p, a.board), `${p.id}: hints reach a solve`);
    // The solve is real, by the independent simulator.
    const b = a.board;
    if (q.mode === 'break') assert.ok(answers[p.id].includes(b.start.join('')) && !simulate(machine, b.start).sorted, `${p.id}: solved on a start that counts`);
    if (q.mode === 'every') assert.ok(answers[p.id].every(k => b.tried.includes(k)), `${p.id}: solved with every wrong start`);
    if (q.mode === 'lights') {
      const lit = b.tried.map(k => simulate(machine, k.split('').map(Number)).lit);
      assert.ok(lit.some((x, i) => lit.indexOf(x) !== i), `${p.id}: two tried starts share lights`);
    }
    if (q.mode === 'build') assert.ok(sorts(fromBoard(b.bars), n), `${p.id}: solved with a sorter`);
    const solvedMove = {break: {type: 'run'}, every: {type: 'claim'}, lights: {type: 'run'}, build: {type: 'test'}}[q.mode];
    assert.equal(move(p, a, solvedMove), null, `${p.id}: no moves after a solve`);
    assert.equal(move(p, a, q.cards === 'binary' ? {type: 'flip', lane: 0} : {type: 'swap', a: 0, b: 1}), null, `${p.id}: no changes after a solve`);

    // Illegal moves change nothing.
    const fresh = freshAttempt(p);
    for (const bad of [null, 'run', {type: 'jump'}, {type: 'swap', a: 0, b: 0}, {type: 'swap', a: 0, b: n}, {type: 'flip', lane: n}, {type: 'bar', slot: -1, lanes: [0, 1]}]) assert.equal(move(p, fresh, bad), null, `${p.id}: rejects ${JSON.stringify(bad)}`);
    assert.equal(move(p, fresh, q.cards === 'binary' ? {type: 'swap', a: 0, b: 1} : {type: 'flip', lane: 0}), null, `${p.id}: the other kind of card change`);
    if (q.mode !== 'build') {
      assert.equal(move(p, fresh, {type: 'bar', slot: 0, lanes: [0, 1]}), null, `${p.id}: the machine is fixed`);
      assert.equal(move(p, fresh, {type: 'test'}), null, `${p.id}: no Test`);
    } else {
      if (machine.length) assert.equal(move(p, fresh, {type: 'bar', slot: 0, lanes: null}), null, `${p.id}: given bars stay`);
      const slot = machine.length;
      assert.equal(move(p, fresh, {type: 'bar', slot, lanes: [1, 1]}), null, `${p.id}: a bar joins two lanes`);
      assert.equal(move(p, fresh, {type: 'bar', slot: q.slots, lanes: [0, 1]}), null, `${p.id}: no extra slot`);
      if (q.adjacent) assert.equal(move(p, fresh, {type: 'bar', slot, lanes: [0, 2]}), null, `${p.id}: neighbors only`);
      // A failed Test shows a wrong start on the board.
      const tested = move(p, fresh, {type: 'test'});
      assert.ok(tested && tested.board.ran && !simulate(fromBoard(tested.board.bars), tested.board.start).sorted, `${p.id}: a failed Test runs a wrong start`);
      assert.equal(move(p, tested, {type: 'test'}), null, `${p.id}: no second Test of the same machine`);
    }
    if (q.mode !== 'every') assert.equal(move(p, fresh, {type: 'claim'}), null, `${p.id}: no That’s all`);
    else {
      const early = move(p, fresh, {type: 'claim'});
      assert.ok(early && early.board.missed && !isSolved(p, early.board), `${p.id}: an early That’s all says there is another`);
      assert.equal(move(p, early, {type: 'claim'}), null, `${p.id}: not twice in a row`);
    }
    const ran = move(p, fresh, {type: 'run'});
    assert.ok(ran && ran.board.ran, `${p.id}: Run`);
    assert.equal(move(p, ran, {type: 'run'}), null, `${p.id}: one Run per start`);

    // Undo keeps the starts already tried on the same machine.
    if (q.mode !== 'build') {
      const changed = move(p, ran, q.cards === 'binary' ? {type: 'flip', lane: 0} : {type: 'swap', a: 0, b: 1});
      const again = move(p, changed, {type: 'run'}) || changed;
      const back = undo(again), kept = {...back, board: mechanicFor(p).carry(p, again.board, back.board)};
      assert.ok(validBoard(p, kept.board), `${p.id}: board after Undo is valid`);
      assert.deepEqual(kept.board.tried, again.board.tried, `${p.id}: Undo keeps tried starts`);
    }

    // Forged saves are rejected.
    const f = fresh.board;
    const forged = [
      {...f, tried: ['9999'.slice(0, n)]}, {...f, tried: [f.start.join(''), f.start.join('')]}, {...f, ran: true},
      {...f, bars: [...f.bars, null]}, {...f, start: f.start.map(() => 1).slice(0, n - 1)}, {...f, claimed: 'yes'}
    ];
    if (q.mode === 'every') forged.push({...f, claimed: true}, {...f, claimed: true, missed: true, tried: answers[p.id]});
    if (q.mode !== 'build') forged.push({...f, tested: true}, {...f, bars: f.bars.map((bar, i) => i ? bar : [bar[1], bar[0]])});
    if (q.mode === 'build' && machine.length) forged.push({...f, bars: f.bars.map((bar, i) => i ? bar : null)});
    if (q.cards !== 'binary') forged.push({...f, start: f.start.map(() => 1)});
    for (const board of forged) assert.equal(validBoard(p, board), false, `${p.id}: rejects ${JSON.stringify(board)}`);
  }

  // Playground: every lane count and both kinds of card; Test agrees with
  // the simulator, and a sorter for four lanes passes with either kind.
  const [pg] = playgrounds;
  let a = freshAttempt(pg);
  assert.ok(validBoard(pg, a.board) && !isSolved(pg, a.board));
  for (const lanes of [2, 3, 4, 5]) {
    a = move(pg, a, {type: 'lanes', lanes}) || a;
    assert.equal(a.board.lanes, lanes);
    for (const cards of ['numbers', 'binary']) {
      a = move(pg, a, {type: 'cards', cards}) || a;
      assert.equal(a.board.cards, cards);
      const tested = move(pg, a, {type: 'test'});
      assert.ok(tested && !simulate(fromBoard(tested.board.bars), tested.board.start).sorted, `${lanes} lanes, ${cards}: an empty machine fails, and Test shows a wrong start`);
      const shuffled = move(pg, a, {type: 'shuffle'}, () => 0.5);
      assert.ok(shuffled && validBoard(pg, shuffled.board), 'Shuffle');
      assert.ok(move(pg, a, {type: 'run'}), 'Run');
    }
  }
  a = move(pg, a, {type: 'lanes', lanes: 4});
  for (const [slot, lanes] of [[0, [0, 1]], [1, [2, 3]], [2, [0, 2]], [3, [1, 3]], [4, [1, 2]]]) a = move(pg, a, {type: 'bar', slot, lanes});
  for (const cards of ['numbers', 'binary']) {
    a = move(pg, a, {type: 'cards', cards}) || a;
    const tested = move(pg, a, {type: 'test'});
    assert.ok(tested.board.tested && !tested.board.ran && !isSolved(pg, tested.board), `${cards}: the sorter passes, and the playground never counts as solved`);
  }
  assert.equal(move(pg, a, {type: 'lanes', lanes: 7}), null);
  assert.equal(move(pg, a, {type: 'bar', slot: 9, lanes: [0, 1]}), null);
  assert.equal(validBoard(pg, {...a.board, bars: a.board.bars.slice(1)}), false);
  return {sortingPuzzles: core.length, playground: 1, sources: sorting.sources.length, hintSteps: steps, theorems: facts};
}
export default validateSorting;
if (process.argv[1] === new URL(import.meta.url).pathname) console.log(JSON.stringify(await validateSorting(), null, 2));
